# Generated by Django 6.0.7 on 2026-07-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsession',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='completed',
        ),
        migrations.AddField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
    ]
