# Generated by Django 6.0.7 on 2026-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('exam', 'question')},
        ),
        migrations.AddField(
            model_name='examsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='score',
        ),
    ]
