# Generated by Django 6.0.7 on 2026-07-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_examsession_options_remove_examsession_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
