# Generated by Django 6.0.7 on 2026-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_studentanswer_feedback_studentanswer_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.AddField(
            model_name='question',
            name='allow_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='allow_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
