# Generated by Django 6.0.7 on 2026-07-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_question_options_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_answers/'),
        ),
    ]
