# Generated by Django 6.0.7 on 2026-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_studentanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='student_answers/files/'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_answers/images/'),
        ),
    ]
