# Generated by Django 6.0.7 on 2026-07-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_studentanswer_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='file_required',
            field=models.BooleanField(default=False),
        ),
    ]
